# Generated by Django 3.1.7 on 2021-03-31 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_faq_ordernumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='ordernumber',
            new_name='orderno',
        ),
    ]
