# Generated by Django 3.1.7 on 2021-03-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_faq_orderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='orderno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
