# Generated by Django 3.1.7 on 2021-03-25 17:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20210325_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
