# Generated by Django 3.1.7 on 2021-06-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_userplace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPlace',
        ),
    ]
