# Generated by Django 3.1.7 on 2021-06-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
