# Generated by Django 3.1.7 on 2021-06-18 12:02

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaces',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.userplaces'),
        ),
    ]
