# Generated by Django 3.1.7 on 2021-06-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210618_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplaces',
            name='menu',
        ),
    ]
